//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.Support.CMATGateway.Proxy.Passport
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PassportCredentialInfo", Namespace = "http://MS.Support.Passport")]
    [System.SerializableAttribute()]
    [ExcludeFromCodeCoverage]
    public partial class PassportCredentialInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretAnswerField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretQuestionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignInNameField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecretAnswer
        {
            get
            {
                return this.SecretAnswerField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SecretAnswerField, value) != true))
                {
                    this.SecretAnswerField = value;
                    this.RaisePropertyChanged("SecretAnswer");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecretQuestion
        {
            get
            {
                return this.SecretQuestionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SecretQuestionField, value) != true))
                {
                    this.SecretQuestionField = value;
                    this.RaisePropertyChanged("SecretQuestion");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignInName
        {
            get
            {
                return this.SignInNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SignInNameField, value) != true))
                {
                    this.SignInNameField = value;
                    this.RaisePropertyChanged("SignInName");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PassportProfileInfo", Namespace = "http://MS.Support.Passport")]
    [System.SerializableAttribute()]
    [ExcludeFromCodeCoverage]
    public partial class PassportProfileInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsChildField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MS.Support.CMATGateway.Proxy.Passport.LiveIDStatus LiveIDStatusField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CountryField, value) != true))
                {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true))
                {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChild
        {
            get
            {
                return this.IsChildField;
            }
            set
            {
                if ((this.IsChildField.Equals(value) != true))
                {
                    this.IsChildField = value;
                    this.RaisePropertyChanged("IsChild");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LastNameField, value) != true))
                {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MS.Support.CMATGateway.Proxy.Passport.LiveIDStatus LiveIDStatus
        {
            get
            {
                return this.LiveIDStatusField;
            }
            set
            {
                if ((this.LiveIDStatusField.Equals(value) != true))
                {
                    this.LiveIDStatusField = value;
                    this.RaisePropertyChanged("LiveIDStatus");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true))
                {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StateField, value) != true))
                {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "LiveIDStatus", Namespace = "http://schemas.datacontract.org/2004/07/MS.Support.Passport.DataModel")]
    public enum LiveIDStatus : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAvailable = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Banned = 2,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://MS.Support.Passport", ConfigurationName = "PassportServiceProxy.IPassportService")]
    public interface IPassportService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://MS.Support.Passport/IPassportService/GetPuidByMemberName", ReplyAction = "http://MS.Support.Passport/IPassportService/GetPuidByMemberNameResponse")]
        //[System.ServiceModel.FaultContractAttribute(typeof(MS.Support.Server.Common.Gateway.GatewayFault), Action = "http://MS.Support.Passport/IPassportService/GetPuidByMemberNameGatewayFaultFault", Name = "GatewayFault", Namespace = "http://schemas.datacontract.org/2004/07/MS.Support.Server.Common.Gateway")]
        long GetPuidByMemberName(string memberName);

        [System.ServiceModel.OperationContractAttribute(Action = "http://MS.Support.Passport/IPassportService/GetCredentialInfo", ReplyAction = "http://MS.Support.Passport/IPassportService/GetCredentialInfoResponse")]
        //[System.ServiceModel.FaultContractAttribute(typeof(MS.Support.Server.Common.Gateway.GatewayFault), Action = "http://MS.Support.Passport/IPassportService/GetCredentialInfoGatewayFaultFault", Name = "GatewayFault", Namespace = "http://schemas.datacontract.org/2004/07/MS.Support.Server.Common.Gateway")]
        MS.Support.CMATGateway.Proxy.Passport.PassportCredentialInfo GetCredentialInfo(long puid);

        [System.ServiceModel.OperationContractAttribute(Action = "http://MS.Support.Passport/IPassportService/GetProfileInfo", ReplyAction = "http://MS.Support.Passport/IPassportService/GetProfileInfoResponse")]
        //[System.ServiceModel.FaultContractAttribute(typeof(MS.Support.Server.Common.Gateway.GatewayFault), Action = "http://MS.Support.Passport/IPassportService/GetProfileInfoGatewayFaultFault", Name = "GatewayFault", Namespace = "http://schemas.datacontract.org/2004/07/MS.Support.Server.Common.Gateway")]
        MS.Support.CMATGateway.Proxy.Passport.PassportProfileInfo GetProfileInfo(long puid);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPassportServiceChannel : MS.Support.CMATGateway.Proxy.Passport.IPassportService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [ExcludeFromCodeCoverage]
    public partial class PassportServiceClient : System.ServiceModel.ClientBase<MS.Support.CMATGateway.Proxy.Passport.IPassportService>, MS.Support.CMATGateway.Proxy.Passport.IPassportService
    {

        public PassportServiceClient()
        {
        }

        public PassportServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public PassportServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public PassportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public PassportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public long GetPuidByMemberName(string memberName)
        {
            return base.Channel.GetPuidByMemberName(memberName);
        }

        public MS.Support.CMATGateway.Proxy.Passport.PassportCredentialInfo GetCredentialInfo(long puid)
        {
            return base.Channel.GetCredentialInfo(puid);
        }

        public MS.Support.CMATGateway.Proxy.Passport.PassportProfileInfo GetProfileInfo(long puid)
        {
            return base.Channel.GetProfileInfo(puid);
        }
    }
}
